name: Build and Deploy Backend #Nom du worflow affiché dans Github

on: # Déclenchement automatique du workflow
  push: # Le déclenchement s'éxécute lorsque l'on push sur la branche main
    branches:
      - main

env: #Variables globales utilisables dans tout le workflow
  # Tag de l'image Docker'
  IMAGE_TAG: latest

jobs:
  # Nom du job
  test-package-build-push-deploy:
    #Machine virtuelle utilisée pour éxécuter les étapes
    runs-on: ubuntu-latest

    # Permissions accordées au workflow
    permissions:
      # autorise la lecture du dépot
      contents: read
      # autorise l'envoi d'images Docker vers GHCR
      packages: write

    steps:
      # Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4
      # Force le nom du repo en lowercase
      - name: Set Image Name to Lowercase
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/room-booking-backend" >> ${GITHUB_ENV}

      # Installation de Java
      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          # Distribution OpenJDK maintenue par Eclipse Temurin
          distribution: temurin
          # Version Java utilisée
          java-version: '25'
          # Mise en cache des dépendances Maven
          cache: maven

      # Exécution des tests
      - name: Run Maven tests
        working-directory: backend
        # Lance tous les tests unitaires et d'intégration
        run: mvn test

      # Création du package Spring Boot
      - name: Package application
        working-directory: backend
        # Génère le JAR exécutable sans relancer les tests
        run: mvn package -DskipTests

      # Authentification à GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # Registre Docker GitHub
          registry: ghcr.io
          # Utilisateur connecté (celui qui déclenche l'action)
          username: ${{ github.actor }}
          # Token GitHub automatiquement fourni
          password: ${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}

      # Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:$IMAGE_TAG \
            -t $IMAGE_NAME:${{ github.sha }} \
            ./backend

      # Publication de l'image Docker
      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:${{ github.sha }}

      # Déploiement sur Render
      - name: Trigger Render deploy hook
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"